apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\For_Windows\2.Accademic\1.CIT_2021-2023\Term4\3495_AdvTopic_Infrastructure\project2\3495_project2\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mysqldb
  name: mysqldb
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    io.kompose.service: mysqldb
  type: LoadBalancer
