apiVersion: apps/v1
kind: Deployment
metadata:
  name: output-deployment
  labels:
    app: output
spec:
  replicas: 2
  selector:
    matchLabels:
      app: output
  template:
    metadata:
      labels:
        app: output
    spec:
      containers:
      - name: output
        image: alexhzzz/output_app:v1
        ports:
        - containerPort: 5000