apiVersion: apps/v1
kind: Deployment
metadata:
  name: ouput
  labels:
    app: ouput
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ouput
  strategy: {}
  template:
    metadata:
      labels:
        app: ouput
    spec:
      containers:
        - image: alexhzzz/output_app:latest
          name: ouput-app
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: ouput-lb
spec:
  type: LoadBalancer
  loadBalancerIP: 34.94.15.198
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    app: ouput
