apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: input
  name: input
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: input
      app: input
  template:
    metadata:
      labels:
        io.kompose.service: input
        app: input
    spec:
      containers:
        - env:
            - name: MYSQLDB_DOCKER_PORT
              valueFrom:
                configMapKeyRef:
                  key: MYSQLDB_DOCKER_PORT
                  name: env
            - name: MYSQLDB_LOCAL_PORT
              valueFrom:
                configMapKeyRef:
                  key: MYSQLDB_LOCAL_PORT
                  name: env
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_DATABASE
                  name: env
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_HOST
                  name: env
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_PASSWORD
                  name: env
            - name: MYSQL_PORT
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_USER
                  name: env
            - name: NODE_DOCKER_PORT
              valueFrom:
                configMapKeyRef:
                  key: NODE_DOCKER_PORT
                  name: env
            - name: NODE_LOCAL_PORT
              valueFrom:
                configMapKeyRef:
                  key: NODE_LOCAL_PORT
                  name: env
          image: stevencchang/input:latest
          name: input-app
          ports:
            - containerPort: 3001
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      restartPolicy: Always
