apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: input
  name: input
spec:
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3001
  selector:
    io.kompose.service: input
  type: LoadBalancer
