apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-auth
  labels:
    app: result-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-auth
  template:
    metadata:
      labels:
        app: result-auth
    spec:
      containers:
        - image: alexhzzz/result_login:latest
          name: result-auth
          env:
            - name: output_host
              value: 35.236.18.249
          ports:
            - containerPort: 3003
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "128Mi"
              cpu: "200m"
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: result-auth-lb
spec:
  type: LoadBalancer
  ports:
    - name: "3003"
      port: 3003
      targetPort: 3003
  selector:
    app: result-auth
